sudo: false
dist: trusty
language: node_js
node_js:
- "4"
- "6"
- "8"
- "stable"
os:
- linux
- osx
before_install:
  - if [[ `node --version` ==  v6* ]]; then npm install -g npm; fi
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install --ignore-scripts
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run test
after_script:
  - greenkeeper-lockfile-upload


jobs:
  include:
    - &integ-test
      stage: integration test
      install: npm install --ignore-scripts
      script: npm run test-integration
      node_js: "4"
      os: linux
    - <<: *integ-test
      node_js: "4"
      os: osx
    - <<: *integ-test
      node_js: "6"
      os: linux
    - <<: *integ-test
      node_js: "6"
      os: osx
    - <<: *integ-test
      node_js: "8"
      os: linux
    - <<: *integ-test
      node_js: "8"
      os: osx
    - <<: *integ-test
      node_js: "stable"
      os: linux
    - <<: *integ-test
      node_js: "stable"
      os: osx
    - stage: npm release
      if: branch = master AND type = push
      node_js: "8"
      script: npm run-script build && npm run semantic-release
